import { STYLE, BRAND, MATERIAL, PATTERN } from "./enums.js";

export const inventory = [
  {
    price: 149,
    sku: crypto.randomUUID(),
    sale: false,
    name: "The Weekender",
    tagline: "The perfect wallet for a night out",
    urls: ["/media/wallets/weekender.jpeg"],
    alts: ["Weekender wallet"],
    style: STYLE.TRIFOLD,
    brand: BRAND.ALLEN,
    pattern: PATTERN.SOLID,
    material: MATERIAL.NYLON,
  },
  {
    price: 329,
    sku: crypto.randomUUID(),
    sale: true,
    name: "The Boss",
    tagline: "Let them know who's boss",
    urls: ["/media/wallets/boss.webp"],
    alts: ["Boss wallet"],
    style: STYLE.BIFOLD,
    brand: BRAND.KERNAL,
    pattern: PATTERN.SOLID,
    material: MATERIAL.LEATHER,
  },
  {
    price: 219,
    sku: crypto.randomUUID(),
    sale: true,
    name: "The Lady",
    tagline: "Feminine. Elegant.",
    urls: ["/media/wallets/lady.jpg"],
    alts: ["Boss wallet"],
    style: STYLE.BIFOLD,
    style: STYLE.CHECK_BOOK,
    brand: BRAND.TRENDIES,
    pattern: PATTERN.DOTTED,
    material: MATERIAL.LEATHER,
  },
  {
    price: 129,
    sku: crypto.randomUUID(),
    sale: true,
    name: "The Mensch",
    tagline: "All around outstanding",
    urls: ["/media/wallets/mensch.jpeg"],
    alts: ["Mensch wallet"],
    style: STYLE.BIFOLD,
    style: STYLE.BIFOLD,
    brand: BRAND.RUNBOX,
    pattern: PATTERN.CHECKERED,
    material: MATERIAL.LEATHER,
  },
  {
    price: 49,
    sku: crypto.randomUUID(),
    sale: false,
    name: "The Basic",
    tagline: "Nothing more, nothing less",
    urls: ["/media/wallets/basic.jpg"],
    alts: ["Basic wallet"],
    style: STYLE.BIFOLD,
    style: STYLE.TRIFOLD,
    brand: BRAND.RGB,
    pattern: PATTERN.CHECKERED,
    material: MATERIAL.LEATHER,
  },
  {
    price: 169,
    sku: crypto.randomUUID(),
    sale: false,
    name: "The Sigma",
    tagline: "You know who you are.",
    urls: ["/media/wallets/sigma.jpeg"],
    alts: ["Sigma wallet"],
    style: STYLE.BIFOLD,
    style: STYLE.BIFOLD,
    brand: BRAND.RUNBOX,
    pattern: PATTERN.CHECKERED,
    material: MATERIAL.METAL,
  },
];

// docs
// https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
