import { STYLE, BRAND, MATERIAL, PATTERN } from "./enums.js";

export const inventory = {
  wallets: [
    {
      price: 49,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Weekender",
      tagline: "The perfect wallet for a night out",
      urls: ["/media/wallets/weekender.jpeg"],
      alts: ["Weekender wallet"],
      style: STYLE.TRIFOLD,
      brand: BRAND.ALLEN,
      pattern: PATTERN.SOLID,
      material: MATERIAL.NYLON,
    },
    {
      price: 129,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Boss",
      tagline: "Let them know who's boss",
      urls: ["/media/wallets/boss.webp"],
      alts: ["Boss wallet"],
      style: STYLE.BIFOLD,
      brand: BRAND.KERNAL,
      pattern: PATTERN.SOLID,
      material: MATERIAL.LEATHER,
    },
    {
      price: 69,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Lady",
      tagline: "Feminine. Elegant.",
      urls: ["/media/wallets/lady.jpg"],
      alts: ["Boss wallet"],
      style: STYLE.CHECK_BOOK,
      brand: BRAND.TRENDIES,
      pattern: PATTERN.DOTTED,
      material: MATERIAL.LEATHER,
    },
    {
      price: 89,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Mensch",
      tagline: "All around outstanding",
      urls: ["/media/wallets/mensch.jpeg"],
      alts: ["Mensch wallet"],
      style: STYLE.BIFOLD,
      brand: BRAND.RUNBOX,
      pattern: PATTERN.CHECKERED,
      material: MATERIAL.LEATHER,
    },
    {
      price: 59,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Basic",
      tagline: "Nothing more, nothing less",
      urls: ["/media/wallets/basic.jpg"],
      alts: ["Basic wallet"],
      style: STYLE.TRIFOLD,
      brand: BRAND.RGB,
      pattern: PATTERN.CHECKERED,
      material: MATERIAL.LEATHER,
    },
    {
      price: 119,
      type: "wallet",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Sigma",
      tagline: "You know who you are.",
      urls: ["/media/wallets/sigma.jpeg"],
      alts: ["Sigma wallet"],
      style: STYLE.BIFOLD,
      brand: BRAND.RUNBOX,
      pattern: PATTERN.CHECKERED,
      material: MATERIAL.METAL,
    },
  ],
  watches: [
    {
      price: 149,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Sportsman",
      tagline: "High speed living",
      urls: ["/media/watches/sportsman.jpeg"],
      alts: ["Sportsman watch"],
      style: STYLE.BLANK,
      brand: BRAND.ALLEN,
      pattern: PATTERN.SLOTTED,
      material: MATERIAL.SILICONE,
    },
    {
      price: 129,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Princess",
      tagline: "Let them know who's boss",
      urls: ["/media/watches/princess.webp"],
      alts: ["Princess watch"],
      style: STYLE.BLANK,
      brand: BRAND.KERNAL,
      pattern: PATTERN.SOLID,
      material: MATERIAL.SILICONE,
    },
    {
      price: 419,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Bossman",
      tagline: "Feminine. Elegant.",
      urls: ["/media/watches/bossman.jpg"],
      alts: ["Bossman watch"],
      style: STYLE.BLANK,
      brand: BRAND.TRENDIES,
      pattern: PATTERN.SOLID,
      material: MATERIAL.METAL,
    },
    {
      price: 339,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: true,
      name: "The Classic",
      tagline: "Timeless time piece",
      urls: ["/media/watches/classic.jpg"],
      alts: ["Classic watch"],
      style: STYLE.BLANK,
      brand: BRAND.RUNBOX,
      pattern: PATTERN.SOLID,
      material: MATERIAL.LEATHER,
    },
    {
      price: 49,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Royal",
      tagline: "Stay regal",
      urls: ["/media/watches/royal.jpg"],
      alts: ["Royal watch"],
      style: STYLE.BLANK,
      brand: BRAND.RGB,
      pattern: PATTERN.TEXTURED,
      material: MATERIAL.SILICONE,
    },
    {
      price: 169,
      type: "watch",
      sku: crypto.randomUUID(),
      sale: false,
      name: "The Madam",
      tagline: "You know who you are.",
      urls: ["/media/watches/madam.jpg"],
      alts: ["Madam watch"],
      style: STYLE.BLANK,
      brand: BRAND.RUNBOX,
      pattern: PATTERN.SOLID,
      material: MATERIAL.LEATHER,
    },
  ],
};

// docs
// https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
